name: legis_core
description: a shared core for legis
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
 
dev_dependencies:  
  pedantic: ^1.9.0
  test: ^1.6.3
