name: legis_server
description: A REST API BackEnd for LEGIS 1.0
version: 0.0.1
author: PMRO <desenv.pmro@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  angel_framework: ^2.1.1 # The core server library.
  angel_auth: ^2.1.5+1 # Supports stateless authentication via JWT
  angel_configuration: ^2.2.0 # Loads application configuration, along with support for .env files.
  angel_production: ^1.0.0 # Production application runner.
  angel_static: ^2.1.3+2 # Static file server
  angel_validate: ^2.0.2 # Allows for validation of input data
  angel_jael: ^2.0.0 # Server-side templating engine
  angel_cors: ^2.0.0

  dartdap: ^0.4.5
  jaguar_jwt: ^2.1.6
  #postgres: ^2.1.1
  dotenv: ^1.0.0
  path: ^1.6.4 
  source_gen: ^0.9.4+4  
  #http_server: ^0.9.8+3
  http_parser: ^3.1.4

  #aqueduct: 3.3.0+1
  mongo_dart: ^0.4.4
  uuid: ^2.2.2
  crossplat_objectid: ^2.1.4  
  collection: ^1.14.13

  legis_core:
    path: ../legis_core

  #esta sobre escrita de dependencias é para resolver um bug no driver postgres 
  #que impede o mesmo de funcionar com dart 2.8.4 e um bug com form data 
  #com dados UTF8(caracteres com acento)
dependency_overrides:
  postgres: ^2.1.1
  http_server:
    git:
      url: https://github.com/dart-lang/http_server.git
      ref: df31d20


dev_dependencies:
  test: ^1.0.0
  #aqueduct_test: ^1.0.0
  angel_hot:  # Hot-reloading support. :) ^2.0.6
  build_runner: ^1.10.0 